version: "3.4"

services:
  admin:
    image: avosa/admin:dev
    build: ./admin/

  artifact:
    image: avosa/artifact:dev
    build: ./artifact/

  auth:
    image: avosa/auth:dev
    build: ./auth/

  blog:
    image: avosa/blog:dev
    build: ./blog/

  cars:
    image: avosa/cars:dev
    build: ./cars/

  cms:
    image: avosa/cms:dev
    build: ./cms/

  comment:
    image: avosa/comment:dev
    build: ./comment/

  comms:
    image: avosa/comms:dev
    build: ./comms/

  entity:
    image: avosa/entity:dev
    build: ./entity/

  funds:
    image: avosa/funds:dev
    build: ./funds/

  game:
    image: avosa/game:dev
    build: ./game/

  leads:
    image: avosa/leads:dev
    build: ./leads/

  logbook:
    image: avosa/logbook:dev
    build: ./logbook/

  notify:
    image: avosa/notify:dev
    build: ./notify/

  quote:
    image: avosa/quote:dev
    build: ./quote/

  secure:
    image: avosa/secure:dev
    build: ./secure/

  service:
    image: avosa/service:dev
    build: ./service/

  shop:
    image: avosa/shop:dev
    build: ./shop/

  stock:
    image: avosa/stock:dev
    build: ./stock/

  theme:
    image: avosa/theme:dev
    build: ./theme/

  vehicle:
    image: avosa/vehicle:dev
    build: ./vehicle/

  vin:
    image: avosa/vin:dev
    build: ./vin/

  wheelo:
    image: avosa/wheelo:dev
    build: ./wheelo/

  www:
    image: avosa/www:dev
    build: ./www/

  xchange:
    image: avosa/xchange:dev
    build: ./xchange/


