version: "3.4"

services:
  cloak:
    image: quay.io/keycloak/keycloak:11.0.2
    command:
      - -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      - KEYCLOAK_USER=admin       #${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=admin   #${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080

  theme:
    image: avosa/theme:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./theme/
    ports:
      - "8093:8093"
    depends_on:
      - cloak
    volumes:
      - ./theme/db/:/db

  folio:
    image: avosa/folio:dev
    build: ./folio/
    ports:
      - "8090:8090"
    volumes:
      - ./folio/db/:/db
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango

  cms:
    image: avosa/cms:dev
    command:
      - --host=http://${IP}:8107
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --client=cms
      - --secret=54e8f43e-da72-4907-8aac-dba7a773af3c
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --blog=http://${IP}:8102
      - --comms=http://${IP}:8085
      - --comment=http://${IP}:8084
    build: ./cms/
    ports:
      - "8107:8107"
    depends_on:
      - folio

  admin:
    image: avosa/admin:dev
    command:
      - --host=http://${IP}:8088
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --client=admin
      - --secret=a9ab17bd-50f5-4cf5-8a08-7f7799173686
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --funds=http://${IP}:8092
      - --game=http://${IP}:8100
      - --stock=http://${IP}:8101
      - --theme=http://${IP}:8093
      - --utility=http://${IP}:8105
      - --vehicle=http://${IP}:8098
      - --wear=http://${IP}:8086
      - --xchange=http://${IP}:8104
      - --house=http://${IP}:8888
      - --parts=http://${IP}:9999
    build: ./admin/
    ports:
      - "8088:8088"
    depends_on:
      - folio

  blog:
    image: avosa/blog:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./blog/
    ports:
      - "8102:8102"
    depends_on:
      - cloak
    volumes:
      - ./blog/db/:/db

  vehicle:
    image: avosa/vehicle:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./vehicle/
    ports:
      - "8098:8098"
    depends_on:
      - cloak
    volumes:
      - ./vehicle/db/:/db

  wear:
    image: avosa/wear:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./wear/
    ports:
      - "8086:8086"
    depends_on:
      - cloak
    volumes:
      - ./wear/db/:/db

  utility:
    image: avosa/utility:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./utility/
    ports:
      - "8105:8105"
    depends_on:
      - cloak
    volumes:
      - ./utility/db/:/db

  parts:
    image: avosa/parts:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./parts/
    ports:
      - "8097:8097"
    depends_on:
      - cloak
    volumes:
      - ./parts/db/:/db

  house:
    image: avosa/house:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./house/
    ports:
      - "8094:8094"
    depends_on:
      - cloak
    volumes:
      - ./house/db/:/db

  comment:
    image: avosa/comment:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./comment/
    ports:
      - "8084:8084"
    depends_on:
      - cloak
    volumes:
      - ./comment/db/:/db

  comms:
    image: avosa/comms:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./comms/
    ports:
      - "8085:8085"
    depends_on:
      - cloak
    volumes:
      - ./comms/db/:/db

  artifact:
    image: avosa/artifact:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./artifact/
    ports:
      - "8082:8082"
    depends_on:
      - cloak
    volumes:
      - ./artifact/db/:/db

  stock:
    image: avosa/stock:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./stock/
    ports:
      - "8101:8101"
    depends_on:
      - cloak
    volumes:
      - ./stock/db/:/db

  vin:
    image: avosa/vin:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./vin/
    ports:
      - "8095:8095"
    depends_on:
      - cloak
    volumes:
      - ./vin/db/:/db

  service:
    image: avosa/service:dev
    build: ./service/
    ports:
      - "8096:8096"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8096
      - --secret=dda189bb-5f76-45ce-bc2d-9e9ef5d5c465
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --stock=http://${IP}:8101
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082

  cars:
    image: avosa/cars:dev
    build: ./cars/
    ports:
      - "8081:8081"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8081
      - --secret=b8ff3b99-d53d-43bb-a73a-7af5cc5d4f89
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --stock=http://${IP}:8093
      - --vehicle=http://${IP}:8098
      - --vin=http://${IP}:8095

  shop:
    image: avosa/shop:dev
    build: ./shop/
    ports:
      - "8083:8083"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8083
      - --secret=b3ffd44b-6024-42bd-924f-35d77c5c08fd
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --stock=http://${IP}:8093

  www:
    image: avosa/www:dev
    build: ./www/
    ports:
      - "8091:8091"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8091
      - --secret=652d8794-4c64-47ed-b641-4b886632a519
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --blog=http://${IP}:8102
      - --stock=http://${IP}:8101
      - --comms=http://${IP}:8085
      - --comment=http://${IP}:8084
