version: "3.7"

services:
  WWWLIVE:
    image: avosa/www:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    depends_on:
      - RouterLIVE
      - FolioLIVE
      - ThemeLIVE
      - CommsLIVE
    networks:
      - mango_net
    ports:
      - "8091:8091"
    command: ["./wait-for-it.sh", "ThemeLIVE:8093", "--", "python", "app.py"]

  RouterLIVE:
    image: avosa/router:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8080:8080"
    networks:
      - mango_net

  FolioLIVE:
    image: avosa/folio:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8090:8090"
    networks:
      - mango_net
    volumes: 
      - /var/db/:/db
    depends_on:
      - RouterLIVE
      - SecureLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  AuthLIVE:
    image: avosa/auth:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8094:8094"
    networks:
      - mango_net
    depends_on:
      - SecureLIVE

  SecureLIVE:
    image: avosa/secure:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8086:8086"
    networks:
      - mango_net
    depends_on:
      - router

  ThemeLIVE:
    image: avosa/theme:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8093:8093"
    networks:
      - mango_net
    depends_on:
      - RouterLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  CommsLIVE:
    image: avosa/comms:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8085:8085"
    networks:
      - mango_net
    volumes: 
      - /var/db/:/db
    depends_on:
      - RouterLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  GateLIVE:
    image: avosa/gate:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mango_net
    depends_on:
      - WWWLIVE
    volumes:
      - /etc/letsencrypt/live/${HOST}/fullchain.pem:/certs/fullchain.pem
      - /etc/letsencrypt/live/${HOST}/privkey.pem:/certs/privkey.pem
      - /etc/letsencrypt/live/${HOST}/:/certs
    command: ["./wait-for-it.sh", "WWWLIVE:8091", "--", "python", "app.py"]

  AdminLIVE:
    image: avosa/admin:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8088:8088"
    networks:
      - "mango_net"
    depends_on:
    - "RouterLIVE"
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  ArtifactLIVE:
    image: avosa/artifact:dev
    environment:
      - RUNMODE=${RUNMODE}
      - HOST=${HOST}
    ports:
      - "8082:8082"
    networks:
      - "mango_net"
    volumes: 
      - /var/db/:/db
    depends_on:
      - router
  www:
    build: 
      context: web/www
      dockerfile: ../../Dockerfile
      args:
        WRKDIR: .
    image: avosa/www:latest
    depends_on:
      - router

networks:
  mango_net:
    driver: bridge
    name: mango_net
