version: "3.4"

services:
  cloak:
    image: quay.io/keycloak/keycloak:11.0.2
    environment:
      - KEYCLOAK_USER=admin       #${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=admin   #${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080

  theme:
    image: avosa/theme:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./theme/
    ports:
      - "8093:8093"
    depends_on:
      - folio
    volumes:
      - ./theme/db/:/db

  folio:
    image: avosa/folio:dev
    build: ./folio/
    ports:
      - "8090:8090"
    volumes:
      - ./folio/db/:/db
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango

  cms:
    image: avosa/cms:dev
    command:
      - --host=http://${IP}:8107
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --client=cms
      - --secret=06ceb2fb-c321-4996-9717-2536cf60b463
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --blog=http://${IP}:8102
    build: ./cms/
    ports:
      - "8107:8107"
    depends_on:
      - folio

  blog:
    image: avosa/blog:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./blog/
    ports:
      - "8102:8102"
    depends_on:
      - cloak
    volumes:
      - ./blog/db/:/db

  vehicle:
    image: avosa/vehicle:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./vehicle/
    ports:
      - "8098:8098"
    depends_on:
      - cloak
    volumes:
      - ./vehicle/db/:/db

  comment:
    image: avosa/comment:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./comment/
    ports:
      - "8084:8084"
    depends_on:
      - cloak
    volumes:
      - ./comment/db/:/db

  comms:
    image: avosa/comms:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./comms/
    ports:
      - "8085:8085"
    depends_on:
      - cloak
    volumes:
      - ./comms/db/:/db

  artifact:
    image: avosa/artifact:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./artifact/
    ports:
      - "8082:8082"
    depends_on:
      - cloak
    volumes:
      - ./artifact/db/:/db

  stock:
    image: avosa/stock:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./stock/
    ports:
      - "8101:8101"
    depends_on:
      - cloak
    volumes:
      - ./stock/db/:/db

  vin:
    image: avosa/vin:dev
    command:
      - --issuer=http://${IP}:8080/auth/realms/mango
    build: ./vin/
    ports:
      - "8095:8095"
    depends_on:
      - cloak
    volumes:
      - ./vin/db/:/db

  cars:
    image: avosa/cars:dev
    build: ./cars/
    ports:
      - "8081:8081"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8081
      - --secret=07fafe59-fd6b-4f77-aa6b-a15768714f77
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --stock=http://${IP}:8101
      - --vin=http://${IP}:8095

  service:
    image: avosa/service:dev
    build: ./service/
    ports:
      - "8096:8096"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8096
      - --secret=441251a7-f584-4a0c-bdfb-501d0e59e1c2
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --stock=http://${IP}:8101

  shop:
    image: avosa/shop:dev
    build: ./shop/
    ports:
      - "8083:8083"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8083
      - --secret=d8fc27f3-d16c-421d-baa1-6b3f4e04e6cb
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --artifact=http://${IP}:8082
      - --stock=http://${IP}:8093

  www:
    image: avosa/www:dev
    build: ./www/
    ports:
      - "8091:8091"
    depends_on:
      - theme
    command:
      - --host=http://${IP}:8091
      - --secret=1a9d2f3f-2090-4c6f-a17b-e7a28236fe25
      - --issuer=http://${IP}:8080/auth/realms/mango
      - --theme=http://${IP}:8093
      - --folio=http://${IP}:8090
      - --blog=http://${IP}:8102
      - --stock=http://${IP}:8101
      - --comms=http://${IP}:8085
