version: "3.7"

services:
  WWWLIVE:
      image: avosa/www:latest
      build: .
      environment:
        - RUNMODE=${RUNMODE}
        - KEYPATH=${KEYPATH}
        - PUBLICKEY=${PUBLICKEY}
        - HOST=${HOST}
      volumes: 
        - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
      depends_on:
        - ThemeLIVE
        - FolioLIVE
        - CommsLIVE
        - ArtifactLIVE
        - AdminLIVE
      networks:
        - mango_net
      ports:
        - "8091:8091"
      command: ["./wait-for-it.sh", "ThemeLIVE:8093", "--", "python", "app.py"]

  RouterLIVE:
    image: avosa/router:latest
    environment:
        - RUNMODE=${RUNMODE}
        - KEYPATH=${KEYPATH}
        - PUBLICKEY=${PUBLICKEY}
        - HOST=${HOST}
    ports:
      - "8080:8080"
    networks:
      - mango_net
    volumes: 
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem

  FolioLIVE:
    image: avosa/folio:latest
    environment:
        - RUNMODE=${RUNMODE}
        - KEYPATH=${KEYPATH}
        - PUBLICKEY=${PUBLICKEY}
        - HOST=${HOST}
    ports:
      - "8090:8090"
    volumes:
      - /var/db/:/db
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    networks:
        - mango_net
    depends_on:
        - RouterLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  SecureLIVE:
    image: avosa/secure:latest
    environment:
        - RUNMODE=${RUNMODE}
        - KEYPATH=${KEYPATH}
        - PUBLICKEY=${PUBLICKEY}
        - PRIVATEKEY=${PRIVATEKEY}
        - HOST=${HOST}
    ports:
      - "8086:8086"
    networks:
      - mango_net
    volumes: 
      - /var/db/:/db
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    depends_on:
        - RouterLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  ThemeLIVE:
    image: avosa/theme:latest
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    volumes: 
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    ports:
      - "8093:8093"
    networks:
      - mango_net
    depends_on:
      - RouterLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  CommsLIVE:
    image: avosa/comms:latest
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    ports:
      - "8085:8085"
    networks:
      - mango_net
    volumes: 
      - /var/db/:/db
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    depends_on:
        - RouterLIVE
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  GateLIVE:
    image: avosa/gate:latest
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - PRIVATEKEY=${PRIVATEKEY}
      - HOST=${HOST}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mango_net
    depends_on:
      - WWWLIVE
    volumes:
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
      - /etc/letsencrypt/live/avosa.co.za/privkey.pem:/certs/privkey.pem
      - /etc/letsencrypt/live/avosa.co.za/.well-known/:/certs/.well-known/
    command: ["./wait-for-it.sh", "WWWLIVE:8091", "--", "python", "app.py"]

  ArtifactLIVE:
    image: avosa/artifact:latest
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    ports:
      - "8082:8082"
    networks:
      - "mango_net"
    volumes: 
      - /var/db/:/db
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    depends_on:
    - "RouterLIVE"
    command: ["./wait-for-it.sh", "RouterLIVE:8080", "--", "python", "app.py"]

  AdminLIVE:
    image: avosa/admin:latest
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    depends_on:
      - FolioLIVE
      - ThemeLIVE
      - SecureLIVE
      - ArtifactLIVE
      - CommsLIVE
    volumes: 
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    networks:
      - mango_net
    ports:
      - "8088:8088"
    command: ["./wait-for-it.sh", "ThemeLIVE:8093", "--", "python", "app.py"]

  AuthLIVE:
    image: avosa/auth:latest
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    volumes: 
      - /etc/letsencrypt/live/avosa.co.za/fullchain.pem:/certs/fullchain.pem
    ports:
      - "8094:8094"
    networks:
      - "mango_net"
    depends_on:
      - "SecureLIVE"
    command: ["./wait-for-it.sh", "SecureLIVE:8086", "--", "python", "app.py"]

networks:
  mango_net:
    driver: bridge
    name: mango_net