package things

import (
	"fmt"

	"github.com/louisevanderlith/db"
	"github.com/louisevanderlith/husk"
)

type Model struct {
	Name string `hsk:"size(50)"`
}

func (o Model) Valid() (bool, error) {
	return husk.ValidateStruct(&o)
}

func seedModel() {
	data := Models{}
	data.Add(Model{Name: "1000", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "280ZX", Manufacturer: &Manufacturer{Record: db.Record{Id: 55}}})
	data.Add(Model{Name: "2CV", Manufacturer: &Manufacturer{Record: db.Record{Id: 14}}})
	data.Add(Model{Name: "5000S", Manufacturer: &Manufacturer{Record: db.Record{Id: 5}}})
	data.Add(Model{Name: "600", Manufacturer: &Manufacturer{Record: db.Record{Id: 8}}})
	data.Add(Model{Name: "6000", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "626", Manufacturer: &Manufacturer{Record: db.Record{Id: 46}}})
	data.Add(Model{Name: "900", Manufacturer: &Manufacturer{Record: db.Record{Id: 66}}})
	data.Add(Model{Name: "914", Manufacturer: &Manufacturer{Record: db.Record{Id: 61}}})
	data.Add(Model{Name: "944", Manufacturer: &Manufacturer{Record: db.Record{Id: 61}}})
	data.Add(Model{Name: "Accord", Manufacturer: &Manufacturer{Record: db.Record{Id: 30}}})
	data.Add(Model{Name: "Alliance", Manufacturer: &Manufacturer{Record: db.Record{Id: 64}}})
	data.Add(Model{Name: "Aries", Manufacturer: &Manufacturer{Record: db.Record{Id: 18}}})
	data.Add(Model{Name: "Aspen", Manufacturer: &Manufacturer{Record: db.Record{Id: 18}}})
	data.Add(Model{Name: "Avanti", Manufacturer: &Manufacturer{Record: db.Record{Id: 73}}})
	data.Add(Model{Name: "Beetle", Manufacturer: &Manufacturer{Record: db.Record{Id: 78}}})
	data.Add(Model{Name: "Bel Air", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Biturbo", Manufacturer: &Manufacturer{Record: db.Record{Id: 44}}})
	data.Add(Model{Name: "Bonneville", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Brat", Manufacturer: &Manufacturer{Record: db.Record{Id: 74}}})
	data.Add(Model{Name: "Bronco II", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Bronco", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Camaro", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Capri", Manufacturer: &Manufacturer{Record: db.Record{Id: 49}}})
	data.Add(Model{Name: "Caprice", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Celica", Manufacturer: &Manufacturer{Record: db.Record{Id: 77}}})
	data.Add(Model{Name: "Century", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "Charger", Manufacturer: &Manufacturer{Record: db.Record{Id: 18}}})
	data.Add(Model{Name: "Citation", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Civic", Manufacturer: &Manufacturer{Record: db.Record{Id: 30}}})
	data.Add(Model{Name: "Classic", Manufacturer: &Manufacturer{Record: db.Record{Id: 63}}})
	data.Add(Model{Name: "Continental", Manufacturer: &Manufacturer{Record: db.Record{Id: 42}}})
	data.Add(Model{Name: "Cordia", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Corvair 500", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Corvair", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Corvette", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Cougar", Manufacturer: &Manufacturer{Record: db.Record{Id: 49}}})
	data.Add(Model{Name: "Country", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "CR-X", Manufacturer: &Manufacturer{Record: db.Record{Id: 30}}})
	data.Add(Model{Name: "CX", Manufacturer: &Manufacturer{Record: db.Record{Id: 13}}})
	data.Add(Model{Name: "Daytona", Manufacturer: &Manufacturer{Record: db.Record{Id: 18}}})
	data.Add(Model{Name: "E150", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "E250", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "E-Class", Manufacturer: &Manufacturer{Record: db.Record{Id: 48}}})
	data.Add(Model{Name: "Electra", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "Escort", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "E-Series", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Esprit Turbo", Manufacturer: &Manufacturer{Record: db.Record{Id: 43}}})
	data.Add(Model{Name: "EXP", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "F150", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "F250", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Fairlane", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Falcon", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Fiero", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Fillmore", Manufacturer: &Manufacturer{Record: db.Record{Id: 23}}})
	data.Add(Model{Name: "Firebird", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Firefly", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Fleetwood", Manufacturer: &Manufacturer{Record: db.Record{Id: 11}}})
	data.Add(Model{Name: "Fury", Manufacturer: &Manufacturer{Record: db.Record{Id: 59}}})
	data.Add(Model{Name: "Galant", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Galaxie", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "GLC", Manufacturer: &Manufacturer{Record: db.Record{Id: 46}}})
	data.Add(Model{Name: "Golf", Manufacturer: &Manufacturer{Record: db.Record{Id: 78}}})
	data.Add(Model{Name: "Grand Marquis", Manufacturer: &Manufacturer{Record: db.Record{Id: 49}}})
	data.Add(Model{Name: "Grand Prix", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "GT350", Manufacturer: &Manufacturer{Record: db.Record{Id: 69}}})
	data.Add(Model{Name: "GT500", Manufacturer: &Manufacturer{Record: db.Record{Id: 69}}})
	data.Add(Model{Name: "GTO", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Horizon", Manufacturer: &Manufacturer{Record: db.Record{Id: 59}}})
	data.Add(Model{Name: "Imperial", Manufacturer: &Manufacturer{Record: db.Record{Id: 13}}})
	data.Add(Model{Name: "Interceptor", Manufacturer: &Manufacturer{Record: db.Record{Id: 37}}})
	data.Add(Model{Name: "Jetta", Manufacturer: &Manufacturer{Record: db.Record{Id: 78}}})
	data.Add(Model{Name: "Laser", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "LeMans", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "LeSabre", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "LTD Crown Victoria", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "LTD", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "LUV", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Lynx", Manufacturer: &Manufacturer{Record: db.Record{Id: 49}}})
	data.Add(Model{Name: "Mark VII", Manufacturer: &Manufacturer{Record: db.Record{Id: 42}}})
	data.Add(Model{Name: "Marquis", Manufacturer: &Manufacturer{Record: db.Record{Id: 49}}})
	data.Add(Model{Name: "MGB", Manufacturer: &Manufacturer{Record: db.Record{Id: 51}}})
	data.Add(Model{Name: "Mini Cooper S", Manufacturer: &Manufacturer{Record: db.Record{Id: 6}}})
	data.Add(Model{Name: "Mini Cooper", Manufacturer: &Manufacturer{Record: db.Record{Id: 6}}})
	data.Add(Model{Name: "Mini", Manufacturer: &Manufacturer{Record: db.Record{Id: 6}}})
	data.Add(Model{Name: "Minx Magnificent", Manufacturer: &Manufacturer{Record: db.Record{Id: 28}}})
	data.Add(Model{Name: "Mirage", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Model T", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Monte Carlo", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Monza", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Mustang", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Omni", Manufacturer: &Manufacturer{Record: db.Record{Id: 18}}})
	data.Add(Model{Name: "Pajero", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Parisienne", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Prelude", Manufacturer: &Manufacturer{Record: db.Record{Id: 30}}})
	data.Add(Model{Name: "Quantum", Manufacturer: &Manufacturer{Record: db.Record{Id: 78}}})
	data.Add(Model{Name: "Quattroporte", Manufacturer: &Manufacturer{Record: db.Record{Id: 44}}})
	data.Add(Model{Name: "Ranger", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Reliant", Manufacturer: &Manufacturer{Record: db.Record{Id: 59}}})
	data.Add(Model{Name: "Riviera", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "Roadrunner", Manufacturer: &Manufacturer{Record: db.Record{Id: 59}}})
	data.Add(Model{Name: "Rockette", Manufacturer: &Manufacturer{Record: db.Record{Id: 20}}})
	data.Add(Model{Name: "RX-7", Manufacturer: &Manufacturer{Record: db.Record{Id: 46}}})
	data.Add(Model{Name: "Scirocco", Manufacturer: &Manufacturer{Record: db.Record{Id: 78}}})
	data.Add(Model{Name: "S-Class", Manufacturer: &Manufacturer{Record: db.Record{Id: 48}}})
	data.Add(Model{Name: "SJ 410", Manufacturer: &Manufacturer{Record: db.Record{Id: 75}}})
	data.Add(Model{Name: "Skyhawk", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "SL-Class", Manufacturer: &Manufacturer{Record: db.Record{Id: 48}}})
	data.Add(Model{Name: "SM", Manufacturer: &Manufacturer{Record: db.Record{Id: 13}}})
	data.Add(Model{Name: "Somerset", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "Space", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Special", Manufacturer: &Manufacturer{Record: db.Record{Id: 10}}})
	data.Add(Model{Name: "Starion", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Sunbird", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Tempest", Manufacturer: &Manufacturer{Record: db.Record{Id: 60}}})
	data.Add(Model{Name: "Tempo", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Thunderbird", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Topaz", Manufacturer: &Manufacturer{Record: db.Record{Id: 49}}})
	data.Add(Model{Name: "Torino", Manufacturer: &Manufacturer{Record: db.Record{Id: 25}}})
	data.Add(Model{Name: "Toronado", Manufacturer: &Manufacturer{Record: db.Record{Id: 56}}})
	data.Add(Model{Name: "Town Car", Manufacturer: &Manufacturer{Record: db.Record{Id: 42}}})
	data.Add(Model{Name: "Tredia", Manufacturer: &Manufacturer{Record: db.Record{Id: 53}}})
	data.Add(Model{Name: "Vanagon", Manufacturer: &Manufacturer{Record: db.Record{Id: 78}}})
	data.Add(Model{Name: "Vega", Manufacturer: &Manufacturer{Record: db.Record{Id: 12}}})
	data.Add(Model{Name: "Volare", Manufacturer: &Manufacturer{Record: db.Record{Id: 59}}})
	data.Add(Model{Name: "W123", Manufacturer: &Manufacturer{Record: db.Record{Id: 48}}})
	data.Add(Model{Name: "W126", Manufacturer: &Manufacturer{Record: db.Record{Id: 48}}})
	data.Add(Model{Name: "W201", Manufacturer: &Manufacturer{Record: db.Record{Id: 48}}})

	var items Models
	err := Ctx.Models.Read(&Model{}, &items)

	if err == nil {
		if len(items) == 0 {
			_, err = Ctx.Models.CreateMulti(data)

			if err != nil {
				fmt.Println("seedModel:", err)
			}
		}
	} else {
		fmt.Println("seedModel:", err)
	}
}
