version: "3.7"

services: 
  AdminAPP:
    image: avosa/admin:${TAG}
    build: ../admin/

  ArtifactAPI:
    image: avosa/artifact:${TAG}
    build: ../artifact/
  
  AuthAPP:
    image: avosa/auth:${TAG}
    build: ../auth/
  
  BlogAPI:
    image: avosa/blog:${TAG}
    build: ../blog/
  
  CarsAPP:
    image: avosa/cars:${TAG}
    build: ../cars/
  
  CommentAPI:
    image: avosa/comment:${TAG}
    build: ../comment/

  EntityAPI:
    image: avosa/entity:${TAG}
    build: ../entity/

  FolioAPI:
    image: avosa/folio:${TAG}
    build: ../folio/
  
  FundsAPI:
    image: avosa/funds:${TAG}
    build: ../funds/

  GameAPI:
    image: avosa/game:${TAG}
    build: ../game/

  GateAPI:
    image: avosa/gate:${TAG}
    build: ../gate/
  
  LogbookAPI:
    image: avosa/logbook:${TAG}
    build: ../logbook/
  
  NotifyAPI:
    image: avosa/notify:${TAG}
    build: ../notify/

  QuoteAPI:
    image: avosa/quote:${TAG}
    build: ../quote/

  RouterAPI:
    image: avosa/router:${TAG}
    build: ../router/

  SecureAPI:
    image: avosa/secure:${TAG}
    build: ../secure/

  ServiceAPI:
    image: avosa/service:${TAG}
    build: ../service/

  ShopAPP:
    image: avosa/shop:${TAG}
    build: ../shop/

  StockAPI:
    image: avosa/stock:${TAG}
    build: ../stock/

  ThemeAPI:
    image: avosa/theme:${TAG}
    build: ../theme/

  VehicleAPI:
    image: avosa/vehicle:${TAG}
    build: ../vehicle/

  VINAPI:
    image: avosa/vin:${TAG}
    build: ../vin/

  WWWAPP:
    image: avosa/www:${TAG}
    build: ../www/
  
  XChangeAPI:
    image: avosa/xchange:${TAG}
    build: ../xchange/